version: "3.2"

services:
  webserver:
    build: {}
    container_name: webserver
    image: semhoun/webserver:${WEBSERVER_VERSION}
    environment:
      - SERVER_NAME="www.docker.test"
      - SERVER_ADMIN="webmaster@docker.test"
    volumes:
      - ./rootfs/www/:/www/
    ports:
      - 8000:80
