version: "3.2"

services:
  webserver:
    build:
      context: .
    container_name: webserver
    image: semhoun/webserver:${WEBSERVER_VERSION}
    environment:
      - SERVER_NAME="www.docker.test"
      - SERVER_ADMIN="webmaster@docker.test"
    volumes:
      - ./www/:/www/
    ports:
      - 8090:80
